image: "python:3.11.5"

before_script:
    - python --version
    - pip install virtualenv
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install wheel setuptools
    - pip install -r requirements.txt

stages:
    - test

test-job:
    stage: test
    script:
        - pytest