name: admire
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.11
  - pip=23.2.1
  - python=3.11.5
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.41.2
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - absl-py==2.0.0
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - annotated-types==0.5.0
      - anyio==3.7.1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.0
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.1.0
      - babel==2.13.0
      - backcall==0.2.0
      - backoff==2.2.1
      - beautifulsoup4==4.12.2
      - bleach==6.0.0
      - blessed==1.20.0
      - cachetools==5.3.1
      - certifi==2023.7.22
      - cffi==1.16.0
      - charset-normalizer==3.3.0
      - click==8.1.7
      - cmake==3.27.6
      - comm==0.1.4
      - contourpy==1.1.1
      - croniter==1.4.1
      - cycler==0.12.0
      - dateutils==0.6.12
      - debugpy==1.8.0
      - decorator==5.1.1
      - deepdiff==6.5.0
      - defusedxml==0.7.1
      - elastic-transport==8.4.1
      - elasticsearch==8.6.2
      - executing==2.0.0
      - fastapi==0.103.2
      - fastjsonschema==2.18.1
      - filelock==3.12.4
      - fonttools==4.43.0
      - fqdn==1.5.1
      - frozenlist==1.4.0
      - fsspec==2023.9.2
      - google-auth==2.23.2
      - google-auth-oauthlib==1.0.0
      - grpcio==1.59.0
      - h11==0.14.0
      - idna==3.4
      - inquirer==3.1.3
      - ipykernel==6.25.2
      - ipython==8.16.1
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.1
      - isoduration==20.11.0
      - itsdangerous==2.1.2
      - jedi==0.19.1
      - jinja2==3.1.2
      - joblib==1.3.2
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.19.1
      - jsonschema-specifications==2023.7.1
      - jupyter==1.0.0
      - jupyter-client==8.3.1
      - jupyter-console==6.6.3
      - jupyter-core==5.3.2
      - jupyter-events==0.7.0
      - jupyter-lsp==2.2.0
      - jupyter-server==2.7.3
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.6
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.25.0
      - jupyterlab-widgets==3.0.9
      - kaleido==0.2.1
      - kiwisolver==1.4.5
      - lightning==2.0.9.post0
      - lightning-cloud==0.5.39
      - lightning-utilities==0.9.0
      - lit==17.0.2
      - llvmlite==0.41.0
      - markdown==3.4.4
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.6.3
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - mistune==3.0.2
      - mpmath==1.3.0
      - multidict==6.0.4
      - nbclient==0.8.0
      - nbconvert==7.9.1
      - nbformat==5.9.2
      - nest-asyncio==1.5.8
      - networkx==3.1
      - notebook==7.0.4
      - notebook-shim==0.2.3
      - numba==0.58.0
      - numpy==1.24.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - oauthlib==3.2.2
      - ordered-set==4.1.0
      - overrides==7.4.0
      - packaging==23.2
      - pandas==1.5.3
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.0.1
      - platformdirs==3.11.0
      - plotly==5.13.1
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.39
      - protobuf==4.24.4
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==13.0.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pydantic==2.1.1
      - pydantic-core==2.4.0
      - pygments==2.16.1
      - pyjwt==2.8.0
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - python-editor==1.0.4
      - python-json-logger==2.0.7
      - python-multipart==0.0.6
      - pytorch-lightning==2.0.9.post0
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - qtconsole==5.4.4
      - qtpy==2.4.0
      - readchar==4.0.5
      - referencing==0.30.2
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.6.0
      - rpds-py==0.10.3
      - rsa==4.9
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - send2trash==1.8.2
      - six==1.16.0
      - sniffio==1.3.0
      - soupsieve==2.5
      - stack-data==0.6.3
      - starlette==0.27.0
      - starsessions==1.3.0
      - sympy==1.12
      - tenacity==8.2.3
      - tensorboard==2.14.1
      - tensorboard-data-server==0.7.1
      - terminado==0.17.1
      - threadpoolctl==3.2.0
      - tinycss2==1.2.1
      - torch==2.0.1
      - torchmetrics==0.11.4
      - torchsummary==1.5.1
      - tornado==6.3.3
      - tqdm==4.64.1
      - traitlets==5.11.2
      - triton==2.0.0
      - tslearn==0.5.3.2
      - types-python-dateutil==2.8.19.14
      - typing-extensions==4.8.0
      - uri-template==1.3.0
      - urllib3==1.26.17
      - uvicorn==0.23.2
      - wcwidth==0.2.8
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.3
      - websockets==11.0.3
      - werkzeug==3.0.0
      - widgetsnbextension==4.0.9
      - yarl==1.9.2
