CNN_PARAMETERS:
  batch_size: '4096'
  decoder_layers: 32,16,8
  encoder_layers: 16,32,64
  latent_dim: '32'
  learning_rate: '0.001'
  max_epochs: '60'
  test_slide: '1'
  train_slide: '30'
  window_size: '60'
PREPROCESSING:
  data_dir: data
  hosts_blacklist: e2015,
  nodes_count_to_process: '200'
  processed_data_dir: data/processed/all_march_top200_withalloc_and_augm_fixed_hours
  raw_data_dir: data/raw
  test_date_range: 2023-03-01,2023-03-30
  test_remove_periods: ''
  train_date_range: 2023-01-06,2023-08-01
  train_remove_periods: 2023-01-31,2023-02-01&2023-02-07,2023-02-12&2023-02-16,2023-04-01&2023-04-07,2023-04-15&2023-05-22,2023-05-23&2023-05-25,2023-05-26&2023-06-13,2023-06-18&2023-06-22,2023-07-15&2023-07-18,2023-07-19&2023-07-26,2023-08-01
  with_cpu_alloc: 'True'
TRAINING:
  enable_checkpointing: 'True'
  full_training_logs_dir: lightning_logs/AE_CNN/2023_11_15-11_30_42
  img_save_dirname: images
  model_type: CNN
  save_top_k: '1'
  seed: '42'
  shuffle: 'False'
  tensorboard_logging_path: lightning_logs
  val_shuffle: 'False'
